name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    name: Publish
    uses: bigbang1112/workflows/.github/workflows/publish-zip.yml@main
    with:
      project: NostalgicCompletionist.csproj
      zip-name: NostalgicCompletionist
      zip-output-dir: NostalgicCompletionist
      zip-ignore: |
        *.pdb
        *.dbg
      dotnet-version: 10.x.x
